= Arquillian Workshop

== Tools Requirements

SCM:: Git client
JVM:: Java 8 is a must to run everything, not business code itself but some test libraries
Docker:: Having Docker 1.12.X installed to run container tests and build images. It doesn't matter if Docker is with Docker-Machine or native linux. Using Docker 1.13 might work but there can be some limitations due https://github.com/docker-java/docker-java. Also Native Docker in Mac/Windows does not work because of bug in docker-java
Kubernetes cluster:: This tool is optional but to run deployment tests it is worth to have it installed locally using minishift (https://github.com/minishift/minishift) or minikube(https://github.com/kubernetes/minikube). Minishift is used in workshop.
Database:: A MongoDB database is required installed locally.
Forge:: Install latest Forge (http://forge.jboss.org/) tool. You can use the IDE plugin or the CLI. During workshop CLI is used
IDE:: In workshop IntelliJ is used but any Java IDE is good.

== Before Starting

When having installed all software mentioned at <<Tools Requirements>> you need to execute next steps:

=== Clone Beer Workshop Project

[source, terminal]
----
> git clone git@github.com:arquillian-testing-microservices/beer-workshop.git
----

=== Install Forge addons

Enter to Beer-Workshop directory and do next commands:

[source, terminal]
----
> forge

[beer-workshop]$ addon-install-from-git --url https://github.com/forge/as-addon  --coordinate org.jboss.forge.addon:as
[beer-workshop]$ addon-install-from-git --url https://github.com/forge/jboss-as-addon  --coordinate org.jboss.forge.addon:jboss-as-wf
----

Then the day before the workshop install Arquillian Addon. We love to show the latest development so again being inside `forge` console run:

[source, terminal]
----
[beer-workshop]$ addon-install-from-git --url https://github.com/forge/arquillian-addon.git
----

=== Docker Images

Pull to your local Docker host next Docker images.

[source, terminal]
----
> docker pull jboss/wildfly:10.1.0.Final
> docker pull mongo:3.2.12
> docker pull redis:3.2.8
----

== Solution

=== JPA Beer Service

Go to root of the project and start `Forge`.

Then being on `jpa-beer-service` directory execute next Forge command:

[source, terminal]
----
[jpa-beer-service]$ arquillian-setup --test-framework junit --container-adapter wildfly-managed
----

After this command all dependencies are setup. Then let's switch to IDE and code first test.

Open `pom.xml` of current exercise and register `asssertj` dependency.

[source, xml]
.jpa-beer-service/pom.xml
----
<dependency>
  <groupId>org.assertj</groupId>
  <artifactId>assertj-core</artifactId>
  <version>3.6.0</version>
  <scope>test</scope>
</dependency>
----

Then we can create the test class in charge of validating that beers can be found:

[source, java]
.jpa-beer-service
----
package org.beer.workshop;

import org.beer.workshop.boundary.Beers;
import org.beer.workshop.entity.Beer;
import org.beer.workshop.tracing.boundary.LoggerProducer;
import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.JavaArchive;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.jboss.shrinkwrap.resolver.api.maven.Maven;
import org.junit.Test;
import org.junit.runner.RunWith;

import javax.inject.Inject;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

@RunWith(Arquillian.class)
public class BeersTest {

    @Deployment
    public static WebArchive createDeployment() {
        WebArchive webArchive = ShrinkWrap.create(WebArchive.class)
                .addClasses(Beers.class, Beer.class, LoggerProducer.class)
                .addAsWebInfResource("persistence-test.xml", "classes/META-INF/persistence.xml")
                .addAsLibraries(Maven.resolver().loadPomFromFile("pom.xml")
                        .importTestDependencies().resolve().withTransitivity()
                        .as(JavaArchive.class));

        return webArchive;

    }

    @Inject
    Beers beers;

    @Test
    public void should_final_all_beers() {

        // Given:

        Beer beer = new Beer();
        beer.setName("Voll Damn");
        beer.setPrice(1.5);
        beer.setAlcohol(7.2);
        beers.persist(beer);

        // When:

        final List<Beer> beers = this.beers.listAll(0, Integer.MAX_VALUE);

        // Then:

        assertThat(beers)
                .hasSize(1)
                .extracting(Beer::getName)
                .contains("Voll Damn");

    }

}
----

Then you can run the test and see how `Wildfly` is downloaded and started, archive deployed, and test executed.

=== JPA Beer Service 2

Now let's write a test that is a black box test by using client approach:

First of all let's add REST-Assured library on `pom.xml`:

[source, xml]
.jpa-beer-service-2/pom.xml
----
<dependency>
  <groupId>io.rest-assured</groupId>
  <artifactId>rest-assured</artifactId>
  <version>3.0.2</version>
  <scope>test</scope>
</dependency>
<dependency>
  <groupId>com.google.code.gson</groupId>
  <artifactId>gson</artifactId>
  <version>2.5</version>
  <scope>test</scope>
</dependency>
----

And then modify `jpa-beer-service-2/src/test/java/org/beer/workshop/BeerEndpointTest.java` to look like:

[source, java]
.jpa-beer-service-2/src/test/java/org/beer/workshop/org.beer.workshop.BeerEndpointTest.java
----
import io.restassured.RestAssured;
import io.restassured.builder.RequestSpecBuilder;
import io.restassured.http.ContentType;
import org.beer.workshop.boundary.BeerEndpoint;
import org.beer.workshop.entity.Beer;
import org.beer.workshop.tracing.boundary.LoggerProducer;
import org.hamcrest.CoreMatchers;
import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.arquillian.test.api.ArquillianResource;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.net.URL;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.hasItems;

@RunWith(Arquillian.class)
public class org.beer.workshop.BeerEndpointTest {

    @Deployment(testable = false)
    public static WebArchive createDeploymentFile() {
        WebArchive webArchive = ShrinkWrap.create(WebArchive.class, "test.war")
                .addPackages(true, BeerEndpoint.class.getPackage())
                .addClasses(Beer.class, LoggerProducer.class)
                .addAsWebInfResource("persistence-test.xml", "classes/META-INF/persistence.xml");

        return webArchive;

    }

    @ArquillianResource
    URL serviceUrl;

    @Test
    public void should_find_all_beers() {

        // Given:

        RequestSpecBuilder requestSpecBuilder = new RequestSpecBuilder();
        requestSpecBuilder.setBaseUri(serviceUrl.toExternalForm() + "rest/beers/");

        createBeer(requestSpecBuilder);

        // When: Then:

        given()
                .contentType(ContentType.JSON)
                .spec(requestSpecBuilder.build())
                .get()
                .then()
                .assertThat()
                .body("name", hasItems("Voll Damn"));


    }

    private void createBeer(RequestSpecBuilder requestSpecBuilder) {
        Beer beer = new Beer();
        beer.setName("Voll Damn");
        beer.setPrice(1.5);
        beer.setAlcohol(7.2);

        given()
                .contentType(ContentType.JSON)
                .spec(requestSpecBuilder.build())
                .body(beer)
                .post()
                .then()
                .assertThat()
                .statusCode(201);
    }

}

----

=== MongoDB Beer Service

In this example we are going to see another way of writing previous test.
To change a bit the logic, currently `MongoDB` database is used instead of JPA with `H2`.

First thing before executing the test, just start `MongoDB` by calling `${MONGO_HOME}/bin/mongod` using default parameters is ok for given test.

Then let's add APE extension for MongoDB and NoSQLUnit (pending to release under universe):

[source, xml]
.pom.xml
----
<dependency>
    <groupId>org.arquillian.ape</groupId>
    <artifactId>arquillian-ape-nosql-mongodb</artifactId>
    <version>2.0.0-alpha.1</version>
    </dependency>
<dependency>
    <groupId>com.lordofthejars</groupId>
    <artifactId>nosqlunit-mongodb</artifactId>
    <version>1.0.0-rc.2</version>
</dependency>
----

Then let's use it to populate data before executing the test:
TEst must look like:

[source, java]
.BeerEndpointTest.java
----
@RunWith(Arquillian.class)
public class BeerEndpointTest {

    @Deployment(testable = false)
    public static WebArchive createDeploymentFile() {
        WebArchive webArchive = ShrinkWrap.create(WebArchive.class, "test.war")
                .addPackages(true, BeerEndpoint.class.getPackage())
                .addClasses(Beer.class, LoggerProducer.class)
                .addAsLibraries(
                        Maven.resolver()
                                .loadPomFromFile("pom.xml")
                                .importCompileAndRuntimeDependencies()
                                .resolve().withTransitivity()
                                .as(JavaArchive.class)
                );

        return webArchive;

    }

    @ArquillianResource
    URL serviceUrl;

    @ArquillianResource
    @MongoDb
    NoSqlPopulator noSqlPopulator;

    @Test
    public void should_find_all_beers() {

        // Given:

        noSqlPopulator
                .forServer("localhost", 27017)
                .withStorage("test")
                .usingDataSet("beer.json")
                .execute();

        RequestSpecBuilder requestSpecBuilder = new RequestSpecBuilder();
        requestSpecBuilder.setBaseUri(serviceUrl.toExternalForm() + "rest/beers/");

        // When: Then:

        given()
                .contentType(ContentType.JSON)
                .spec(requestSpecBuilder.build())
                .get()
                .then()
                .assertThat()
                .body("name", hasItems("Voll Damm"));


    }

    @After
    public void cleanCollection() {
        noSqlPopulator.forServer("localhost", 27017)
                .withStorage("test")
                .clean();
    }

}

----

Finally you can stop `MongoDB`.

=== MongoDB Beer Service Docker

In this case, the application is updated to use Docker.

Prior to write any test you need to create the image of *Beer Service* by running next Maven command from project directory:

[source, terminal]
----
> mvn clean package -DskipTests
> mvn docker:build
----

After that, Docker image `brewery/beer-service:1.0.0-SNAPSHOT` is created.

Then if you navigate to `src/test/docker` directory, you'll see the `docker-compose` that is defined to start `beer-service` Docker image linked to a MongoDB Docker image.

First of all add next dependencies:

[source, xml]
.mongodb-beer-service-docker/pom.xml
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-junit-standalone</artifactId>
    <type>pom</type>
    <scope>test</scope>
    </dependency>
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-cube-docker</artifactId>
    <type>pom</type>
    <scope>test</scope>
</dependency>
----

And remove:

* `org.arquillian.universe:arquillian-junit`
* `Default Maven Profile`
* Container definition in `arquillian.xml`

Finally open `org.beer.workshop.BeerEndpointTest`, removes `@Deployment` method and enrich test with Docker data.
Test might look like:

...


Also there is a `BeerWarehouse` class that uses `Redis` key-value NoSQL database to maintain the stock of beers.
To write a test for this class, instead of using `docker-compose`, we are going to use Container Object DSL approach.

Test must look like:

[source, java]
----
@RunWith(Arquillian.class)
public class BeerWarehouseTest {

    @DockerContainer
    Container redis = Container.withContainerName("warehouse")
                            .fromImage("redis:3.2.6")
                            .withPortBinding(6379)
                            .build();

    @Test
    public void should_decreaase_stock_when_beer_new_beer() {
        // Given:
        BeerWarehouse beerWarehouse =
                new BeerWarehouse(redis.getIpAddress(), redis.getBindPort(6379));

        // When:
        beerWarehouse.increaseStock("1", 100);
        beerWarehouse.buyBeer("1", 15);

        // Then:
        assertThat(beerWarehouse.remainingStock("1")).isEqualTo(85);

    }

}
----

IMPORTANT: Arquillian Cube always start everything `docker-compose.yml` definitions (including default locations) + Container Objects at the same time. So you can mix  both approaches.

=== Ingredients Service

Let's run this test using Apache Tomcat.
To configure it let's use Forge again.

Go to `ingredients-service` and run `forge`:

[source, terminal]
----
ingredients-service]$ arquillian-setup --test-framework junit --container-adapter tomcat-managed --container-adapter-version 8.0.42
----

After that you can exit Forge console, open the IDE and write your test.

First of all let's add REST-Assured dependency:

[source, xml]
.pom.xml
----
<dependency>
  <groupId>io.rest-assured</groupId>
  <artifactId>rest-assured</artifactId>
  <version>3.0.2</version>
  <scope>test</scope>
</dependency>
----

Then the test must looks like:

[source, java]
.IngredientsServiceTest.java
----
@RunWith(Arquillian.class)
public class IngredientsTest {

    @Deployment(testable = false)
    public static WebArchive createDeployment() {
        return ShrinkWrap.create(WebArchive.class, "ingredients.war").addPackages(true, Ingredients.class.getPackage())
                .addClasses(Ingredient.class)
                .addAsLibraries(Maven.resolver().loadPomFromFile("pom.xml")
                .importCompileAndRuntimeDependencies().resolve().withTransitivity().as(JavaArchive.class));
    }

    @ArquillianResource
    URL ingredientsService;

    @Test
    public void should_get_ingredients_by_beer_name() throws URISyntaxException {

        RequestSpecBuilder requestSpecBuilder = new RequestSpecBuilder();
        requestSpecBuilder.setBaseUri(ingredientsService.toURI());

        RestAssured.given()
                .contentType(ContentType.JSON)
                .spec(requestSpecBuilder.build())
                .pathParam("beerName", "Voll Damm")
                .get("{beerName}")
                .then()
                .assertThat()
                .contentType(ContentType.JSON)
                .body("$.size()", CoreMatchers.is(4));

    }

}
----

[IMPORTANT]
====
You need to update `arquillian.xml` and create a `tomcat8-server.xml` and `tomcat-users.xml` accordantly to be able to deploy aplication. See them in `ingredients-service/src/test/resources`.
====

